In [1]:
###########################################################################################
#                                  Name:Bhushan Joshi                                     #
#                                  Enrollment:2162270307050                               #
#                                  Div:G                                                  #
#                                  Government Polytechnic Porbandar                       #
###########################################################################################

#Practical 10: Write a Pandas program to implement following operation
# to find and drop the missing values from the given dataset
# to remove the duplicates from the given dataset

In [2]:
import pandas as pd
df = pd.read_csv('/kaggle/input/nifty50-stock-market-data/TATAMOTORS.csv')
# Display the first 20 rows of the original dataset
print("Original Dataset (first 20 rows):")
print(df.head(20))
# Drop missing values
df = df.dropna()
# Remove duplicates
df = df.drop_duplicates()
# Display the first 20 rows of the cleaned dataset
print("\nCleaned Dataset (first 20 rows):")
print(df.head(20))

Original Dataset (first 20 rows):
          Date Symbol Series  Prev Close    Open    High     Low    Last  \
0   2000-01-03  TELCO     EQ      201.60  207.40  217.25  207.40  217.00
1   2000-01-04  TELCO     EQ      216.75  217.00  219.00  206.00  211.90
2   2000-01-05  TELCO     EQ      208.20  194.00  217.80  194.00  213.10
3   2000-01-06  TELCO     EQ      213.25  215.00  229.90  215.00  222.00
4   2000-01-07  TELCO     EQ      222.10  224.00  239.90  223.10  239.90
5   2000-01-10  TELCO     EQ      239.90  259.00  259.10  248.00  259.10
6   2000-01-11  TELCO     EQ      258.85  260.00  260.00  238.15  238.15
7   2000-01-12  TELCO     EQ      238.15  240.00  246.00  229.00  242.45
8   2000-01-13  TELCO     EQ      240.25  243.00  245.00  231.60  233.00
9   2000-01-14  TELCO     EQ      235.45  234.95  243.00  233.00  239.80
10  2000-01-17  TELCO     EQ      239.05  242.95  258.10  242.95  251.00
11  2000-01-18  TELCO     EQ      250.65  251.00  252.50  245.05  250.00
12  2000-01-19  TELCO     EQ      248.00  251.00  257.90  242.60  249.50
13  2000-01-20  TELCO     EQ      250.50  250.00  250.00  233.60  234.00
14  2000-01-21  TELCO     EQ      235.70  230.10  233.80  225.50  231.10
15  2000-01-24  TELCO     EQ      232.20  230.00  235.90  213.65  213.65
16  2000-01-25  TELCO     EQ      213.65  200.35  204.90  196.60  196.60
17  2000-01-27  TELCO     EQ      196.60  190.00  193.00  180.90  180.90
18  2000-01-28  TELCO     EQ      180.90  171.00  182.00  168.35  175.00
19  2000-01-31  TELCO     EQ      175.20  171.15  188.70  170.05  178.60

     Close    VWAP   Volume      Turnover  Trades  Deliverable Volume  \
0   216.75  214.28   676126  1.448775e+13     NaN                 NaN
1   208.20  209.50   679215  1.422962e+13     NaN                 NaN
2   213.25  210.33  1120951  2.357684e+13     NaN                 NaN
3   222.10  225.29  1968998  4.435932e+13     NaN                 NaN
4   239.90  236.32  2199431  5.197636e+13     NaN                 NaN
5   258.85  257.20  1720542  4.425303e+13     NaN                 NaN
6   238.15  246.63  1207916  2.979082e+13     NaN                 NaN
7   240.25  237.13   938579  2.225646e+13     NaN                 NaN
8   235.45  237.31   565754  1.342609e+13     NaN                 NaN
9   239.05  239.04  1024725  2.449504e+13     NaN                 NaN
10  250.65  252.65  1482994  3.746834e+13     NaN                 NaN
11  248.00  248.46   792347  1.968666e+13     NaN                 NaN
12  250.50  249.51  1221042  3.046608e+13     NaN                 NaN
13  235.70  242.37   557949  1.352323e+13     NaN                 NaN
14  232.20  230.09   696339  1.602198e+13     NaN                 NaN
15  213.65  223.44  1125168  2.514078e+13     NaN                 NaN
16  196.60  198.54   706121  1.401945e+13     NaN                 NaN
17  180.90  182.54  1728526  3.155243e+13     NaN                 NaN
18  175.20  174.95  2671887  4.674572e+13     NaN                 NaN
19  179.70  181.20  2850688  5.165394e+13     NaN                 NaN

    %Deliverble
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12          NaN
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN

Cleaned Dataset (first 20 rows):
            Date      Symbol Series  Prev Close     Open     High      Low  \
2850  2011-06-01  TATAMOTORS     EQ     1095.30  1096.00  1097.00  1075.60
2851  2011-06-02  TATAMOTORS     EQ     1079.90  1070.00  1070.00  1042.20
2852  2011-06-03  TATAMOTORS     EQ     1048.20  1048.00  1058.00  1014.25
2853  2011-06-06  TATAMOTORS     EQ     1023.80  1011.50  1031.80  1010.25
2854  2011-06-07  TATAMOTORS     EQ     1023.70  1017.00  1033.80  1015.65
2855  2011-06-08  TATAMOTORS     EQ     1027.20  1022.90  1043.65  1021.00
2856  2011-06-09  TATAMOTORS     EQ     1028.55  1029.00  1030.95  1003.40
2857  2011-06-10  TATAMOTORS     EQ     1021.15  1023.40  1024.35  1011.00
2858  2011-06-13  TATAMOTORS     EQ     1019.60  1016.00  1018.75  1004.10
2859  2011-06-14  TATAMOTORS     EQ     1010.30  1008.50  1009.90   981.15
2860  2011-06-15  TATAMOTORS     EQ      984.00   984.00   998.10   974.20
2861  2011-06-16  TATAMOTORS     EQ      994.15   987.50   999.00   980.15
2862  2011-06-17  TATAMOTORS     EQ      983.65   991.95   992.60   976.20
2863  2011-06-20  TATAMOTORS     EQ      980.95   981.50   983.95   925.55
2864  2011-06-21  TATAMOTORS     EQ      931.00   938.00   949.75   930.00
2865  2011-06-22  TATAMOTORS     EQ      936.20   945.00   945.55   927.35
2866  2011-06-23  TATAMOTORS     EQ      935.90   935.00   951.95   926.25
2867  2011-06-24  TATAMOTORS     EQ      945.00   948.25   972.40   948.25
2868  2011-06-27  TATAMOTORS     EQ      966.45   957.00   984.40   950.25
2869  2011-06-28  TATAMOTORS     EQ      977.75   984.00   990.50   967.80

         Last    Close     VWAP   Volume      Turnover   Trades  \
2850  1077.25  1079.90  1083.36  2412309  2.613407e+14  76698.0
2851  1046.15  1048.20  1050.62  2604237  2.736056e+14  74650.0
2852  1024.60  1023.80  1031.52  3600090  3.713581e+14  94611.0
2853  1022.20  1023.70  1020.38  2076683  2.119014e+14  64914.0
2854  1028.00  1027.20  1027.38  2117760  2.175745e+14  56772.0
2855  1027.50  1028.55  1034.22  2069956  2.140799e+14  64859.0
2856  1021.15  1021.15  1015.55  3029331  3.076443e+14  76581.0
2857  1017.00  1019.60  1017.23  2051336  2.086678e+14  72247.0
2858  1009.55  1010.30  1010.40  1804138  1.822898e+14  48207.0
2859   981.15   984.00   990.25  3593062  3.558044e+14  94163.0
2860   993.60   994.15   987.93  3376870  3.336110e+14  97878.0
2861   984.20   983.65   988.39  1759555  1.739128e+14  44612.0
2862   978.50   980.95   983.66  1387205  1.364540e+14  34974.0
2863   936.00   931.00   950.14  2402227  2.282459e+14  66508.0
2864   936.60   936.20   939.59  3090153  2.903463e+14  71589.0
2865   936.00   935.90   935.46  2151715  2.012845e+14  54880.0
2866   944.85   945.00   942.71  2797950  2.637662e+14  71391.0
2867   966.30   966.45   961.22  2526169  2.428203e+14  66346.0
2868   976.50   977.75   973.26  2165506  2.107590e+14  74536.0
2869   983.60   984.70   980.14  1741799  1.707208e+14  51225.0

      Deliverable Volume  %Deliverble
2850           1152083.0       0.4776
2851           1149341.0       0.4413
2852           1472425.0       0.4090
2853            451682.0       0.2175
2854            805423.0       0.3803
2855            587834.0       0.2840
2856           1186233.0       0.3916
2857            732007.0       0.3568
2858            617337.0       0.3422
2859           1847731.0       0.5142
2860           1115540.0       0.3303
2861            625102.0       0.3553
2862            503848.0       0.3632
2863            818414.0       0.3407
2864           1378901.0       0.4462
2865            873700.0       0.4060
2866           1218233.0       0.4354
2867           1199305.0       0.4748
2868           1021177.0       0.4716
2869            675878.0       0.3880